### ISSUE TITLE
Confluence doesn't have asciidoc styles by default

### ISSUE THREAD

**Issue by Ivan-Lymar** [madhead/doktor#36]
`[blue]#Api usage#`
will be transformed to 
`<span class="blue">Api usage</span>`

I expect to see this span in blue color, but seeing just black. Need to find a way of exporting asciidoc *.css files to confluence.

**Comment by madhead** [comment]
- [ ] Wrap generated content into some pre-defined class, like `doktor`.
- [x] Create a stylesheet (copy Asciidoctor's default one) that applies only to `.doktor` children (to be done by space owners)
- [x] "Browse" (at the ribbon on top of the Confluence) -> "Space Admin" (from the dropdown) -> "Stylesheet" (under "LOOK AND FEEL" section on the left). Provide the stylesheet from previous step.

**Comment by madhead** [comment]
```
// AsciiDoc built-in roles
@if $include-asciidoc-role-classes {
  div.unbreakable {
    page-break-inside: avoid;
  }

  .big {
    font-size: larger;
  }
  
  .small {
    font-size: smaller;
  }

  @each $decoration in (underline, overline, line-through) {
    .#{$decoration} {
      text-decoration: $decoration;
    }
  }

  // colors must be quoted or else they may get converted to hex in compression output mode
  @each $color in ('aqua', 'black', 'blue', 'fuchsia', 'gray', 'green', 'lime', 'maroon', 'navy', 'olive', 'purple', 'red', 'silver', 'teal', 'white', 'yellow') {
    .#{$color} {
      color: scale-color(string-to-color($color), $lightness: $rainbow-lightness);
    }
  
    .#{$color}-background {
      background-color: scale-color(string-to-color($color), $lightness: $rainbow-bg-lightness);
    }
  }

  //*:not(code) > .comment {
  //  background: yellow;
  //}
}
```
