### ISSUE TITLE
JENKINS-49699: Doktor plugin affected by JEP-200

### ISSUE THREAD

**Issue by madhead** [madhead/doktor#59]
See more @ https://issues.jenkins-ci.org/browse/JENKINS-49699

**Comment by dibi-codes** [comment]
Any chance to get this fixed? Unfortunately this is a blocker for us. The plugin works just fine on our Jenkins Master but throws the JEP-200 exception on our external build nodes.

**Comment by madhead** [comment]
@dabeck, sorry, I am not working with Jenkins anymore (stopped right after writing this plugin). I don't even understand what's this about as those security changes were released later. Do you have any ideas how to fix it?

**Comment by dibi-codes** [comment]
I just came up with a solution. I installed [this plugin](https://github.com/jenkinsci/kotlin-v1-stdlib-jdk8-plugin) and now it works. Don't know if this is the actual solution but it works :D

**Comment by madhead** [comment]
I am happy to hear that! So, is something needed from Doktor? Probably, declare that plugin as a dependency?
