### ISSUE TITLE
Problems with Confluence Cloud

### ISSUE THREAD

**Issue by dibi-codes** [madhead/doktor#63]
I'm trying to upload markdown to Confluence.
I think I properly configured the server like this:
```
server: https://<our_sub_domain>.atlassian.net/wiki
```
The API doc looks pretty similar to the one stated here:
https://developer.atlassian.com/cloud/confluence/rest/#api-content-post

As soon as I try to publish a new file to confluence the plugin throws an exception:

```
ERROR: Error while uploading ../workspace/Changelog.md document to confluence: by.dev.madhead.doktor.confluence.ConfluenceException: HTTP Exception 404 
```

Changelog.md looks like this:
```
---
title: Changelog
parent: 423460889
---
# Changelog
<content>
```

The API doc says that an error 404 is returned while:
>Returned if the calling user does not have permission to view the requested content.

But my user is actually an admin user which should be able to.

Any suggestions what I am missing? Has anyone successfully used this plugin with confluence cloud?

**Comment by madhead** [comment]
Hello, @dabeck!

Have you tried without `/wiki` at the end?

**Comment by dibi-codes** [comment]
@madhead yes unfortunately not working as well

Just did some `curl` test which is working well:
```
curl --request POST \
  --url 'https://<subdomain>.atlassian.net/wiki/rest/api/content' \
  --user 'user@domain.com:<apikey>' \
  --header 'Accept: application/json' \
  --header 'Content-Type: application/json' \
  --data '{
  "title": "test",
  "type": "page",
  "space": {
    "key": "SPACE"
  },
  "status": "current",
  "ancestors": [
    {
      "id": "423460889"
    }
  ],
  "body": {
    "storage": {
      "value": "bla",
      "representation": "storage"
    }
  }
}'
```
I'm not that familiar with kotlin right now but it looks like it's pretty much the same JSON generated by the plugin
